---

- name: Set datacenter
  ansible.builtin.set_fact:
    vcdc: "{{ vc_fact_datacenter1 }}"

- name: "Create dvSwitch"
  block:

    - name: "Create dvSwitch {{ vcdc }}"
      community.vmware.vmware_dvswitch:
        datacenter: "{{ vcdc }}"
        switch: "dvSwitch-nested"
        version: 6.6.0
        mtu: 9000
        uplink_quantity: 1
        state: present
      run_once: true

    - name: Time out to process
      ansible.builtin.pause:
        seconds: 10

    - name: "Add Host to dVS dvSwitch-nested"
      community.vmware.vmware_dvs_host:
        esxi_hostname: "{{ hostvars[groups['esxi'][my_idx]].NESTEDVMIP }}"
        switch_name: "dvSwitch-nested"
        vmnics:
          - vmnic1
        state: present

    - name: Time out to process
      ansible.builtin.pause:
        seconds: 10

    - name: Create no-vlan portgroup
      community.vmware.vmware_dvs_portgroup:
        portgroup_name: "{{ vc_fact_deployment_network }}"
        switch_name: "dvSwitch-nested"
        vlan_id: 0
        num_ports: 120
        port_binding: static
        state: present

  module_defaults:
    group/vmware:
      hostname: "{{ hostvars[groups['vc'][0]].NESTEDVMIP }}"
      username: 'administrator@{{ vc_fact_domain }}'
      password: "{{ vc_fact_password }}"
      validate_certs: false
