---

- name: Set up hosts
  hosts: localhost
  connection: local
  become: false
  gather_facts: false

  tasks:

    - name: Add host to group esxi
      ansible.builtin.add_host:
        name: '{{ item }}'
        groups: esxi
      loop: '{{ target_hosts | list }}'

    - name: Add host to group vc
      ansible.builtin.add_host:
        name: '{{ item }}'
        groups: vc
      loop: '{{ target_vcs | list }}'

  tags:
    - always

- name: Create nested VM's
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    templocation: "{{ ansible_env.HOME }}/build"
    mountpath: '/data/export/share'
    version: "7"
    esximemory: "131072"
    esxicpu: "20"
    testingesxi: false
    testingvc: false

  collections:
    - community.general
    - vmware.vmware

  module_defaults:
    group/vmware:
      hostname: "{{ lookup('ansible.builtin.env', 'MAINVCHOSTNAME') }}"
      username: "{{ lookup('ansible.builtin.env', 'MAINVCUSERNAME') }}"
      password: "{{ lookup('ansible.builtin.env', 'MAINVCPASSWORD') }}"
      validate_certs: false

  tasks:

    - name: Set up configs
      block:
        - name: Needed packages on system
          ansible.builtin.include_tasks: packlocal.yml
      tags:
        - packlocal
        - never

    - block:
        - name: Include vars of vcenter_host-7.yml
          ansible.builtin.include_vars:
            file: vcenter_host-7.yml

      when: '"7" in version'

    - block:
        - name: Include vars of vcenter_host-8.yml
          ansible.builtin.include_vars:
            file: vcenter_host-8.yml

      when: '"8" in version'

    - name: Deploy
      block:
        - name: Deploy ova of ESXi
          ansible.builtin.include_tasks: esxinested.yml
          loop: "{{ groups['esxi'] | list }}"
          loop_control:
            loop_var: loop_bms
            index_var: my_idx
      tags:
        - esxinested

    - name: Deploy ova of VC
      block:
        - name: Setup VC
          ansible.builtin.include_tasks: vcnested.yml
          loop: "{{ groups['vc'] | list }}"
          loop_control:
            loop_var: loop_bms_vc
            index_var: my_idx_vc
      tags:
        - vcnested

- name: ESXi add vcenter
  hosts: localhost
  connection: local
  gather_facts: false
  serial: 1
  vars:
    bootstrap: true
    nfsetup: true
    nfsiso: false
    localcy: false

  tags:
    - hostvcenter

  collections:
    - community.general
    - community.vmware

  tasks:

    - name: Set up vCenter
      block:
        - name: Add host to vcenter
          ansible.builtin.include_tasks: addhosts_vcenter.yml
          loop: "{{ groups['esxi'] | list }}"
          loop_control:
            loop_var: loop_bms
            index_var: my_idx

        - name: Add dvs to vcenter and add host to dvs
          ansible.builtin.include_tasks: dvs_hosts_vcenter.yml
          loop: "{{ groups['esxi'] | list }}"
          loop_control:
            loop_var: loop_bms
            index_var: my_idx

      tags:
        - vcenterhost

- name: REMOVE nested VM's
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    removevsphere: false
    createcron: false
    cleanupcron: false
    showinfo: true
    getcert: true
    installcert: true

  collections:
    - community.general
    - community.vmware

  module_defaults:
    group/vmware:
      hostname: "{{ lookup('ansible.builtin.env', 'MAINVCHOSTNAME') }}"
      username: "{{ lookup('ansible.builtin.env', 'MAINVCUSERNAME') }}"
      password: "{{ lookup('ansible.builtin.env', 'MAINVCPASSWORD') }}"
      validate_certs: false

  tasks:

    - name: Remove vSphere environment
      ansible.builtin.include_tasks: vsphere_remove.yml
      loop: "{{ groups['esxi'] | list }}"
      loop_control:
        loop_var: loop_bms
        index_var: my_idx
      vars:
        host_fact_name: "{{ hostvars[groups['esxi'][my_idx]].inventory_hostname }}"

    - name: Remove VC
      ansible.builtin.include_tasks: vsphere_remove.yml
      loop: "{{ groups['vc'] | list }}"
      loop_control:
        loop_var: loop_bms
        index_var: my_idx
      vars:
        host_fact_name: "{{ hostvars[groups['vc'][my_idx]].inventory_hostname }}"

    - name: Gather info
      block:
        - name: Set cron
          ansible.builtin.include_tasks: cronjob.yml

        - name: Show vCenter IP
          ansible.builtin.debug:
            msg: "***** {{ host_fact_name }} VCENTER IP ADDRESS *****"
          loop: "{{ groups['vc'] | list }}"
          loop_control:
            loop_var: loop_bms
            index_var: my_idx
          vars:
            host_fact_name: "{{ hostvars[groups['vc'][my_idx]]['NESTEDVMIP'] }}"

        - name: Remove file vcenterip
          ansible.builtin.file:
            path: /tmp/vcenterip
            state: absent
          run_once: true

        - name: Dump vCenter IP to file
          ansible.builtin.lineinfile:
            line: "{{ host_fact_name }}"
            path: /tmp/vcenterip
            create: yes
            insertafter: EOF
          loop: "{{ groups['vc'] | list }}"
          loop_control:
            loop_var: loop_bms
            index_var: my_idx
          vars:
            host_fact_name: "{{ hostvars[groups['vc'][my_idx]]['NESTEDVMIP'] }}"
      when: showinfo | bool

    - name: Certs VC
      ansible.builtin.include_tasks: getcerts.yml
      loop: "{{ groups['vc'] | list }}"
      loop_control:
        loop_var: loop_bms
        index_var: my_idx
      vars:
        host_fact_name: "{{ hostvars[groups['vc'][my_idx]]['NESTEDVMIP'] }}"


  tags:
    - removevsphere
